# backend/scripts/generate_full_glossary.py
import json
import os

# Referencia oficial para validación
REF_OFICIAL = "Glosario INCIBE (2021) / NIST IR 7298"

# --- LISTA MAESTRA DE TÉRMINOS (A-Z) ---
glossary_data = [
    # A
    {"term_en": "Access Control", "term_es": "Control de Acceso", "definition_en": "The process of granting or denying specific requests to obtain and use information.", "definition_es": "Proceso que permite o deniega el uso de recursos mediante identificación, autenticación y autorización.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Access Control List", "term_es": "Lista de Control de Acceso (ACL)", "acronym": "ACL", "definition_en": "A list of permissions associated with an object.", "definition_es": "Lista que especifica qué usuarios tienen permiso para acceder a un recurso y qué operaciones pueden realizar.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Accountability", "term_es": "Rendición de Cuentas", "definition_en": "The property ensuring actions of an entity can be traced uniquely to that entity.", "definition_es": "Capacidad de rastrear las acciones de una entidad de forma inequívoca hasta dicha entidad.", "category": "Governance", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Advanced Persistent Threat", "term_es": "Amenaza Persistente Avanzada", "acronym": "APT", "definition_en": "An adversary with sophisticated expertise and significant resources.", "definition_es": "Ataque complejo y continuo dirigido a una entidad específica, generalmente patrocinado por estados o mafias.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Adware", "term_es": "Adware", "definition_en": "Software that automatically displays advertising material.", "definition_es": "Software que muestra publicidad no deseada, a menudo instalado sin el consentimiento claro del usuario.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Algorithm", "term_es": "Algoritmo", "definition_en": "A finite set of step-by-step instructions for computation.", "definition_es": "Conjunto ordenado de operaciones sistemáticas que permite hacer un cálculo (base de la criptografía).", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Antivirus", "term_es": "Antivirus", "definition_en": "Software used to identify and remove malware.", "definition_es": "Programa diseñado para prevenir, detectar y eliminar software malicioso.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Asset", "term_es": "Activo de Información", "definition_en": "Anything that has value to an organization.", "definition_es": "Cualquier recurso (datos, software, hardware, personal) que tiene valor para la organización.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Asymmetric Encryption", "term_es": "Cifrado Asimétrico", "definition_en": "Cryptography that uses two keys: a public key and a private key.", "definition_es": "Sistema criptográfico que utiliza un par de claves (pública y privada) para cifrar y descifrar.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Attack Vector", "term_es": "Vector de Ataque", "definition_en": "The path or means by which a hacker can gain access to a computer.", "definition_es": "Ruta o método utilizado por un atacante para obtener acceso no autorizado a un sistema.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Audit", "term_es": "Auditoría", "definition_en": "Independent review and examination of records.", "definition_es": "Examen sistemático para determinar si las actividades cumplen con las normativas de seguridad.", "category": "Governance", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Authentication", "term_es": "Autenticación", "definition_en": "Verifying the identity of a user, process, or device.", "definition_es": "Proceso de verificación de la identidad de un usuario (contraseñas, biometría).", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Availability", "term_es": "Disponibilidad", "definition_en": "Ensuring timely and reliable access to and use of information.", "definition_es": "Garantía de que la información esté accesible y utilizable cuando se requiera.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # B
    {"term_en": "Backdoor", "term_es": "Puerta Trasera", "definition_en": "An undocumented way of gaining access to a computer system.", "definition_es": "Método oculto para eludir la autenticación y obtener acceso remoto no autorizado.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Backup", "term_es": "Copia de Seguridad", "definition_en": "A copy of files and programs made to facilitate recovery.", "definition_es": "Duplicado de datos para permitir su recuperación en caso de pérdida o ataque.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Biometrics", "term_es": "Biometría", "definition_en": "Automated methods of identifying based on physical characteristics.", "definition_es": "Tecnologías que miden características físicas (huellas, iris) para autenticar la identidad.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Black Hat", "term_es": "Hacker de Sombrero Negro", "definition_en": "A hacker who violates computer security for maliciousness or personal gain.", "definition_es": "Ciberdelincuente que viola la seguridad con intenciones maliciosas o delictivas.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Blockchain", "term_es": "Blockchain", "definition_en": "A distributed ledger technology that uses cryptography.", "definition_es": "Tecnología de registro distribuido que garantiza integridad mediante bloques enlazados.", "category": "Emerging Tech", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Blue Team", "term_es": "Equipo Azul", "definition_en": "The group responsible for defending an enterprise's information systems.", "definition_es": "Equipo defensivo encargado de proteger la organización contra ciberataques.", "category": "Incident Response", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Botnet", "term_es": "Botnet", "definition_en": "A network of compromised computers under remote command.", "definition_es": "Red de dispositivos infectados controlados remotamente para realizar ataques masivos.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Brute Force Attack", "term_es": "Ataque de Fuerza Bruta", "definition_en": "Attempting multiple combinations of passwords to gain access.", "definition_es": "Método para descifrar contraseñas probando todas las combinaciones posibles.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Buffer Overflow", "term_es": "Desbordamiento de Búfer", "definition_en": "A condition where more input is placed into a buffer than the capacity allocated.", "definition_es": "Fallo donde un programa escribe más datos de los permitidos en memoria, permitiendo ejecutar código malicioso.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Bug Bounty", "term_es": "Recompensa por Errores", "definition_en": "A program offering rewards for finding security vulnerabilities.", "definition_es": "Programa que premia a investigadores por encontrar y reportar fallos de seguridad.", "category": "Governance", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Business Continuity Plan", "term_es": "Plan de Continuidad de Negocio", "acronym": "BCP", "definition_en": "A plan to continue operations if a place of business is affected by different levels of disaster.", "definition_es": "Plan logístico para recuperar y restaurar funciones críticas tras una interrupción no planificada.", "category": "Governance", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},

    # C
    {"term_en": "Certificate Authority", "term_es": "Autoridad de Certificación (CA)", "acronym": "CA", "definition_en": "A trusted entity that issues and revokes public key certificates.", "definition_es": "Entidad de confianza que emite certificados digitales para verificar identidades.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Chain of Custody", "term_es": "Cadena de Custodia", "definition_en": "A process that tracks the movement of evidence.", "definition_es": "Procedimiento que garantiza la integridad de las evidencias digitales desde su recolección hasta el juicio.", "category": "Incident Response", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Ciphertext", "term_es": "Texto Cifrado", "definition_en": "Data that has been encrypted.", "definition_es": "Información transformada mediante cifrado, ilegible sin la clave.", "category": "Cryptography", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cloud Computing", "term_es": "Computación en la Nube", "definition_en": "A model for enabling ubiquitous network access to a shared pool of computing resources.", "definition_es": "Modelo que permite acceso bajo demanda a recursos informáticos a través de Internet.", "category": "Emerging Tech", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cold Site", "term_es": "Sitio Frío", "definition_en": "A backup facility that has the necessary electrical and physical components but no computer equipment.", "definition_es": "Instalación de respaldo con infraestructura básica pero sin equipos informáticos instalados.", "category": "Governance", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Compliance", "term_es": "Cumplimiento (Compliance)", "definition_en": "Adherence to regulatory, legal, and company mandates.", "definition_es": "Adhesión a leyes y normativas de seguridad (ej. RGPD, ISO 27001).", "category": "Governance", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Confidentiality", "term_es": "Confidencialidad", "definition_en": "Preserving authorized restrictions on information access.", "definition_es": "Garantía de que la información solo es accesible por entidades autorizadas.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cookie", "term_es": "Cookie", "definition_en": "A piece of state information supplied by a Web server to a browser.", "definition_es": "Pequeño fichero enviado por un sitio web que se almacena en el navegador del usuario para rastrear actividad.", "category": "Privacy", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Critical Infrastructure", "term_es": "Infraestructura Crítica", "definition_en": "Assets so vital that their incapacity would have a debilitating impact on security.", "definition_es": "Sistemas esenciales (energía, agua, transporte) cuyo fallo afectaría gravemente a la sociedad.", "category": "Governance", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cross-Site Scripting", "term_es": "XSS", "acronym": "XSS", "definition_en": "A vulnerability that allows attackers to inject malicious code into a website.", "definition_es": "Vulnerabilidad que permite inyectar scripts maliciosos en páginas web vistas por otros usuarios.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cryptography", "term_es": "Criptografía", "definition_en": "The discipline that embodies principles for the transformation of data to hide its content.", "definition_es": "Ciencia de cifrar información para protegerla de accesos no autorizados.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cyber Attack", "term_es": "Ciberataque", "definition_en": "An attack via cyberspace targeting an enterprise's use of cyberspace.", "definition_es": "Intento deliberado de dañar o acceder sin autorización a sistemas informáticos.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Cyber Espionage", "term_es": "Ciberespionaje", "definition_en": "The act of obtaining secrets without the permission of the holder of the information.", "definition_es": "Uso de redes informáticas para obtener secretos industriales, políticos o militares.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},

    # D
    {"term_en": "Dark Web", "term_es": "Web Oscura", "definition_en": "Encrypted network content that is not indexed by search engines.", "definition_es": "Parte de Internet no indexada y accesible solo con software específico, a menudo asociada a actividades ilícitas.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Data Breach", "term_es": "Brecha de Datos", "definition_en": "The unauthorized movement or disclosure of sensitive information.", "definition_es": "Incidente de seguridad donde información sensible es robada o expuesta a no autorizados.", "category": "Incident Response", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Data Integrity", "term_es": "Integridad de Datos", "definition_en": "The property that data has not been altered in an unauthorized manner.", "definition_es": "Garantía de que los datos son exactos y no han sido modificados sin autorización.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Data Loss Prevention", "term_es": "Prevención de Pérdida de Datos (DLP)", "acronym": "DLP", "definition_en": "Strategy to ensure that end users do not send sensitive or critical information outside the corporate network.", "definition_es": "Tecnologías para detectar y prevenir la fuga de información confidencial.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Decryption", "term_es": "Descifrado", "definition_en": "The process of transforming ciphertext into plaintext.", "definition_es": "Proceso de convertir datos cifrados a su forma original legible.", "category": "Cryptography", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Deepfake", "term_es": "Deepfake", "definition_en": "Synthetic media in which a person in an existing image or video is replaced with someone else's likeness.", "definition_es": "Vídeo o audio manipulado con IA para hacer que una persona parezca decir o hacer algo que no hizo.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Defense in Depth", "term_es": "Defensa en Profundidad", "definition_en": "Information security strategy integrating people, technology, and operations capabilities to establish variable barriers.", "definition_es": "Uso de múltiples capas de seguridad para proteger los activos si una capa falla.", "category": "Fundamentals", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Demilitarized Zone", "term_es": "Zona Desmilitarizada (DMZ)", "acronym": "DMZ", "definition_en": "A physical or logical subnetwork that contains and exposes an organization's external-facing services.", "definition_es": "Red aislada que sitúa los servicios públicos (web, correo) separándolos de la red interna privada.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Denial of Service", "term_es": "Denegación de Servicio (DoS)", "acronym": "DoS", "definition_en": "The prevention of authorized access to resources or the delaying of time-critical operations.", "definition_es": "Ataque que busca inutilizar un sistema saturándolo de peticiones.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Digital Certificate", "term_es": "Certificado Digital", "definition_en": "An electronic document used to prove the ownership of a public key.", "definition_es": "Documento digital que vincula una clave pública con la identidad de una persona o entidad.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Digital Forensics", "term_es": "Informática Forense", "definition_en": "The recovery and investigation of material found in digital devices.", "definition_es": "Ciencia de recuperar e investigar datos de dispositivos digitales para uso legal.", "category": "Incident Response", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Digital Signature", "term_es": "Firma Digital", "definition_en": "A mathematical scheme for verifying the authenticity of digital messages or documents.", "definition_es": "Mecanismo criptográfico para verificar la autenticidad e integridad de un documento digital.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Distributed Denial of Service", "term_es": "DDoS", "acronym": "DDoS", "definition_en": "A DoS attack using multiple computers to inundate the target.", "definition_es": "Ataque DoS realizado desde múltiples fuentes simultáneamente (botnet).", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Domain Name System", "term_es": "DNS", "acronym": "DNS", "definition_en": "The hierarchical and decentralized naming system for computers using the Internet Protocol.", "definition_es": "Sistema que traduce nombres de dominio legibles (ej. google.com) a direcciones IP.", "category": "Network Security", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Drive-by Download", "term_es": "Descarga Drive-by", "definition_en": "Unintended download of computer software from the Internet.", "definition_es": "Descarga de malware que ocurre automáticamente al visitar un sitio web infectado, sin acción del usuario.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},

    # E
    {"term_en": "Encryption", "term_es": "Cifrado", "definition_en": "The process of encoding information.", "definition_es": "Conversión de datos en un formato ilegible para proteger su confidencialidad.", "category": "Cryptography", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "End-to-End Encryption", "term_es": "Cifrado de Extremo a Extremo", "definition_en": "System where only the communicating users can read the messages.", "definition_es": "Sistema donde solo el emisor y receptor pueden leer los mensajes, impidiendo el acceso a intermediarios.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Ethical Hacking", "term_es": "Hacking Ético", "definition_en": "Authorized practice of bypassing system security to identify potential data breaches.", "definition_es": "Práctica autorizada de penetrar sistemas para encontrar vulnerabilidades y reportarlas.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Exploit", "term_es": "Exploit", "definition_en": "A piece of software, data or a sequence of commands that takes advantage of a bug.", "definition_es": "Código diseñado para aprovechar una vulnerabilidad específica en un sistema.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Exposure", "term_es": "Exposición", "definition_en": "A state of being unprotected and vulnerable to an attack.", "definition_es": "Condición de estar desprotegido o accesible a amenazas.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # F
    {"term_en": "False Negative", "term_es": "Falso Negativo", "definition_en": "A security incident that is not detected by a security system.", "definition_es": "Fallo de un sistema de seguridad al no detectar una amenaza real.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "False Positive", "term_es": "Falso Positivo", "definition_en": "An alert that incorrectly indicates that malicious activity is occurring.", "definition_es": "Alerta de seguridad generada por una actividad legítima y no maliciosa.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Firewall", "term_es": "Cortafuegos", "definition_en": "A network security system that monitors and controls incoming and outgoing network traffic.", "definition_es": "Dispositivo o software que filtra el tráfico de red según reglas de seguridad.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Firmware", "term_es": "Firmware", "definition_en": "Permanent software programmed into a read-only memory.", "definition_es": "Software básico integrado en el hardware que controla su funcionamiento.", "category": "Fundamentals", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Forensics", "term_es": "Forense", "definition_en": "Scientific tests or techniques used in connection with the detection of crime.", "definition_es": "Análisis técnico post-incidente para determinar causas y evidencias.", "category": "Incident Response", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},

    # G
    {"term_en": "Gateway", "term_es": "Puerta de Enlace", "definition_en": "A network point that acts as an entrance to another network.", "definition_es": "Dispositivo que conecta dos redes con protocolos diferentes (ej. red local e Internet).", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Grey Hat", "term_es": "Sombrero Gris", "definition_en": "A hacker who may violate laws or ethical standards, but without the malicious intent of a black hat.", "definition_es": "Hacker que actúa a veces ilegalmente pero sin intenciones maliciosas puras, a menudo para exponer fallos.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},

    # H
    {"term_en": "Hacker", "term_es": "Hacker", "definition_en": "An unauthorized user who attempts to or gains access to an information system.", "definition_es": "Persona con conocimientos técnicos avanzados que explora o vulnera sistemas informáticos.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Hacktivist", "term_es": "Hacktivista", "definition_en": "A hacker whose goals are political or social.", "definition_es": "Hacker que ataca sistemas por motivaciones políticas, sociales o ideológicas.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Hardening", "term_es": "Bastionado", "definition_en": "The process of securing a system by reducing its vulnerability surface.", "definition_es": "Proceso de asegurar un sistema reduciendo sus puntos vulnerables (deshabilitar servicios, configurar reglas).", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Hash", "term_es": "Hash", "definition_en": "A function that converts an input of letters and numbers into an encrypted output of a fixed length.", "definition_es": "Cadena alfanumérica única generada a partir de un archivo para verificar su integridad.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Honeypot", "term_es": "Honeypot (Señuelo)", "definition_en": "A decoy system used to trap and study hackers.", "definition_es": "Sistema trampa diseñado para atraer atacantes y analizar sus técnicas.", "category": "Security Controls", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Hot Site", "term_es": "Sitio Caliente", "definition_en": "A fully functional backup site that allows for immediate recovery of operations.", "definition_es": "Centro de respaldo completamente equipado y listo para operar inmediatamente tras un desastre.", "category": "Governance", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "HTTPS", "term_es": "HTTPS", "acronym": "HTTPS", "definition_en": "Extension of HTTP using encryption.", "definition_es": "Versión segura del protocolo web que cifra la comunicación.", "category": "Network Security", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # I
    {"term_en": "Identity Management", "term_es": "Gestión de Identidades (IAM)", "definition_en": "The organizational process for identifying, authenticating and authorizing individuals.", "definition_es": "Administración de los ciclos de vida de las identidades de usuarios y sus privilegios.", "category": "Fundamentals", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Identity Theft", "term_es": "Robo de Identidad", "definition_en": "The fraudulent acquisition and use of a person's private identifying information.", "definition_es": "Uso fraudulento de la información personal de alguien para cometer delitos en su nombre.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Incident Response", "term_es": "Respuesta a Incidentes", "definition_en": "The approach taken to manage the aftermath of a security breach or cyberattack.", "definition_es": "Proceso organizado para detectar, contener y recuperar la organización tras un ciberataque.", "category": "Incident Response", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Information Security", "term_es": "Seguridad de la Información", "definition_en": "The practice of protecting information by mitigating information risks.", "definition_es": "Protección de la información contra acceso, uso, divulgación o destrucción no autorizados.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Insider Threat", "term_es": "Amenaza Interna", "definition_en": "A threat that comes from within the organization itself.", "definition_es": "Riesgo de seguridad proveniente de empleados o socios con acceso autorizado.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Integrity", "term_es": "Integridad", "definition_en": "Assurance that data has not been tampered with.", "definition_es": "Garantía de que la información es exacta y no ha sido modificada sin autorización.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Internet of Things", "term_es": "Internet de las Cosas (IoT)", "acronym": "IoT", "definition_en": "The network of physical objects that are embedded with sensors and connected to the internet.", "definition_es": "Red de objetos físicos (electrodomésticos, vehículos) conectados a Internet.", "category": "Emerging Tech", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Intrusion Detection System", "term_es": "IDS", "acronym": "IDS", "definition_en": "A device or software application that monitors a network for malicious activity.", "definition_es": "Sistema que monitoriza la red para detectar actividades sospechosas y alertar.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Intrusion Prevention System", "term_es": "IPS", "acronym": "IPS", "definition_en": "A network security tool that continuously monitors a network for malicious activity and takes action to prevent it.", "definition_es": "Sistema que detecta y bloquea activamente las intrusiones en la red.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "IP Address", "term_es": "Dirección IP", "definition_en": "A numerical label assigned to each device connected to a computer network.", "definition_es": "Etiqueta numérica que identifica a un dispositivo en una red.", "category": "Network Security", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "ISO 27001", "term_es": "ISO 27001", "definition_en": "International standard for information security management.", "definition_es": "Estándar internacional para la gestión de la seguridad de la información en organizaciones.", "category": "Governance", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},

    # K
    {"term_en": "Key", "term_es": "Clave (Criptográfica)", "definition_en": "A piece of information that determines the functional output of a cryptographic algorithm.", "definition_es": "Información secreta usada para controlar operaciones criptográficas (cifrado/descifrado).", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Keylogger", "term_es": "Keylogger", "definition_en": "Surveillance software that has the capability to record every keystroke you make.", "definition_es": "Software espía que registra las pulsaciones del teclado para robar contraseñas.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # L
    {"term_en": "Least Privilege", "term_es": "Mínimo Privilegio", "definition_en": "The concept that a user should have the minimum set of privileges necessary to perform their job.", "definition_es": "Principio de otorgar solo los permisos estrictamente necesarios para realizar una tarea.", "category": "Fundamentals", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Logic Bomb", "term_es": "Bomba Lógica", "definition_en": "A piece of code intentionally inserted into a software system that will set off a malicious function when specified conditions are met.", "definition_es": "Código malicioso que se activa bajo condiciones específicas (ej. una fecha).", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},

    # M
    {"term_en": "Macro Virus", "term_es": "Macro Virus", "definition_en": "A virus that is written in a macro language.", "definition_es": "Virus escrito en el lenguaje de macros de aplicaciones (ej. Word, Excel) que se ejecuta al abrir el archivo.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Malware", "term_es": "Malware", "definition_en": "Software that is specifically designed to disrupt, damage, or gain unauthorized access to a computer system.", "definition_es": "Término general para software malicioso (virus, gusanos, troyanos).", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Man-in-the-Middle", "term_es": "Man-in-the-Middle (MitM)", "acronym": "MitM", "definition_en": "An attack where the attacker secretly relays and possibly alters the communication between two parties.", "definition_es": "Ataque donde el agresor intercepta la comunicación entre dos partes sin que lo sepan.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Metadata", "term_es": "Metadatos", "definition_en": "Data that describes other data.", "definition_es": "Datos que describen el contenido, calidad y características de otros datos (ej. autor, fecha).", "category": "Fundamentals", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Multi-Factor Authentication", "term_es": "Autenticación Multifactor (MFA)", "acronym": "MFA", "definition_en": "An electronic authentication method in which a user is granted access only after successfully presenting two or more pieces of evidence.", "definition_es": "Uso de dos o más mecanismos (algo que sabes, tienes o eres) para verificar identidad.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # N
    {"term_en": "Network Segmentation", "term_es": "Segmentación de Red", "definition_en": "Splitting a computer network into subnetworks.", "definition_es": "División de una red en subredes más pequeñas para mejorar seguridad y rendimiento.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "NIST", "term_es": "NIST", "definition_en": "National Institute of Standards and Technology.", "definition_es": "Instituto Nacional de Estándares y Tecnología de EE.UU., clave en ciberseguridad.", "category": "Governance", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Non-Repudiation", "term_es": "No Repudio", "definition_en": "Assurance that the sender of information is provided with proof of delivery and the recipient is provided with proof of the sender's identity.", "definition_es": "Garantía de que una parte no puede negar la autoría de una acción o mensaje.", "category": "Fundamentals", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},

    # O
    {"term_en": "Open Source Intelligence", "term_es": "OSINT", "acronym": "OSINT", "definition_en": "Data collected from publicly available sources to be used in an intelligence context.", "definition_es": "Inteligencia obtenida de fuentes de acceso público (redes sociales, webs).", "category": "Incident Response", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Operating System", "term_es": "Sistema Operativo", "definition_en": "System software that manages computer hardware, software resources, and provides common services.", "definition_es": "Software principal que gestiona el hardware y permite ejecutar aplicaciones.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # P
    {"term_en": "Packet Sniffing", "term_es": "Análisis de Paquetes", "definition_en": "The practice of gathering, collecting, and logging some or all packets that pass through a computer network.", "definition_es": "Interceptación y registro de tráfico de red para análisis.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Patch", "term_es": "Parche", "definition_en": "A set of changes to a computer program or its supporting data designed to update, fix, or improve it.", "definition_es": "Actualización de software para corregir errores o vulnerabilidades.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Payload", "term_es": "Carga Útil", "definition_en": "The component of a computer virus that executes a malicious activity.", "definition_es": "Parte del malware que realiza la acción maliciosa (ej. cifrar datos).", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Penetration Testing", "term_es": "Pentesting", "definition_en": "The practice of testing a computer system, network or web application to find security vulnerabilities.", "definition_es": "Ataques simulados autorizados para evaluar la seguridad de un sistema.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Phishing", "term_es": "Phishing", "definition_en": "The fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity.", "definition_es": "Suplantación de identidad por correo para robar credenciales o datos.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Plaintext", "term_es": "Texto Plano", "definition_en": "Text that is not computationally tagged, specially formatted, or written in code.", "definition_es": "Datos sin cifrar, legibles directamente.", "category": "Cryptography", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Polymorphic Virus", "term_es": "Virus Polimórfico", "definition_en": "A complicated computer virus that affects data types and functions.", "definition_es": "Virus que cambia su código cada vez que se replica para evadir antivirus.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Privacy", "term_es": "Privacidad", "definition_en": "The ability of an individual or group to seclude themselves or information about themselves.", "definition_es": "Derecho a controlar los propios datos personales.", "category": "Governance", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Privilege Escalation", "term_es": "Escalada de Privilegios", "definition_en": "The act of exploiting a bug to gain elevated access.", "definition_es": "Obtención de permisos superiores a los autorizados explotando un fallo.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Protocol", "term_es": "Protocolo", "definition_en": "A set of rules governing the exchange or transmission of data.", "definition_es": "Conjunto de reglas que permiten la comunicación entre dispositivos.", "category": "Network Security", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Proxy Server", "term_es": "Servidor Proxy", "definition_en": "A server that acts as an intermediary for requests from clients seeking resources from other servers.", "definition_es": "Intermediario en las conexiones de red que mejora privacidad y seguridad.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Public Key", "term_es": "Clave Pública", "definition_en": "A cryptographic key that can be obtained and used by anyone to encrypt messages.", "definition_es": "Clave compartida públicamente usada para cifrar mensajes destinados al propietario.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Public Key Infrastructure", "term_es": "PKI", "acronym": "PKI", "definition_en": "A set of roles, policies, and procedures needed to create, manage, distribute, use, store, and revoke digital certificates.", "definition_es": "Infraestructura para gestionar claves y certificados digitales.", "category": "Cryptography", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},

    # Q
    {"term_en": "Quantum Computing", "term_es": "Computación Cuántica", "definition_en": "Computing using quantum-mechanical phenomena.", "definition_es": "Computación basada en principios cuánticos, potencial amenaza para el cifrado actual.", "category": "Emerging Tech", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},

    # R
    {"term_en": "Ransomware", "term_es": "Ransomware", "definition_en": "Malware that encrypts the victim's data and demands payment.", "definition_es": "Malware que cifra archivos y exige rescate para recuperarlos.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Red Team", "term_es": "Equipo Rojo", "definition_en": "An independent group that challenges an organization to improve its effectiveness.", "definition_es": "Equipo ofensivo que simula ataques reales para probar las defensas.", "category": "Incident Response", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Remote Access Trojan", "term_es": "Troyano de Acceso Remoto (RAT)", "acronym": "RAT", "definition_en": "A malware program that includes a back door for administrative control.", "definition_es": "Malware que permite control total remoto del equipo infectado.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Risk", "term_es": "Riesgo", "definition_en": "The potential for loss, damage or destruction of an asset.", "definition_es": "Probabilidad de que una amenaza explote una vulnerabilidad causando daño.", "category": "Governance", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Risk Assessment", "term_es": "Evaluación de Riesgos", "definition_en": "The process of identifying, estimating, and prioritizing risks.", "definition_es": "Proceso de identificar y analizar riesgos para determinar su impacto.", "category": "Governance", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Rootkit", "term_es": "Rootkit", "definition_en": "A collection of computer software, typically malicious, designed to enable access to a computer or an area of its software that is not otherwise allowed.", "definition_es": "Software malicioso que oculta su existencia y permite acceso privilegiado continuo.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Router", "term_es": "Router", "definition_en": "A networking device that forwards data packets between computer networks.", "definition_es": "Dispositivo que dirige el tráfico entre diferentes redes.", "category": "Network Security", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # S
    {"term_en": "Sandbox", "term_es": "Sandbox", "definition_en": "A security mechanism for separating running programs.", "definition_es": "Entorno aislado para ejecutar programas de forma segura sin afectar al sistema.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Secure Shell", "term_es": "SSH", "acronym": "SSH", "definition_en": "A cryptographic network protocol for operating network services securely over an unsecured network.", "definition_es": "Protocolo para acceso remoto seguro y cifrado.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Security Operations Center", "term_es": "SOC", "acronym": "SOC", "definition_en": "A centralized unit that deals with security issues on an organizational and technical level.", "definition_es": "Centro de operaciones donde se monitoriza y defiende la seguridad de la organización.", "category": "Incident Response", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Session Hijacking", "term_es": "Secuestro de Sesión", "definition_en": "The exploitation of a valid computer session to gain unauthorized access.", "definition_es": "Robo de una sesión de usuario activa para acceder sin credenciales.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Sniffing", "term_es": "Sniffing", "definition_en": "Monitoring network traffic.", "definition_es": "Captura y análisis de tráfico de red.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Social Engineering", "term_es": "Ingeniería Social", "definition_en": "Psychological manipulation of people into performing actions or divulging confidential information.", "definition_es": "Manipulación psicológica para que usuarios revelen información confidencial.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Spam", "term_es": "Spam", "definition_en": "Unsolicited junk email.", "definition_es": "Correo electrónico no deseado enviado masivamente.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Spear Phishing", "term_es": "Spear Phishing", "definition_en": "An email-spoofing attack that targets a specific organization or individual.", "definition_es": "Phishing dirigido y personalizado contra un objetivo específico.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Spoofing", "term_es": "Suplantación (Spoofing)", "definition_en": "A situation in which a person or program successfully identifies as another by falsifying data.", "definition_es": "Falsificación de identidad (IP, email, web) para engañar a sistemas o usuarios.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Spyware", "term_es": "Spyware", "definition_en": "Software that enables a user to obtain covert information about another's computer activities.", "definition_es": "Malware que recopila información del usuario sin su conocimiento.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "SQL Injection", "term_es": "Inyección SQL", "acronym": "SQLi", "definition_en": "A code injection technique used to attack data-driven applications.", "definition_es": "Ataque que inserta código SQL malicioso en formularios para manipular bases de datos.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Steganography", "term_es": "Esteganografía", "definition_en": "The practice of concealing a file, message, image, or video within another file, message, image, or video.", "definition_es": "Técnica de ocultar información dentro de otros archivos (ej. imágenes) para que pase desapercibida.", "category": "Cryptography", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Symmetric Encryption", "term_es": "Cifrado Simétrico", "definition_en": "An encryption method in which the same key is used to encrypt and decrypt the message.", "definition_es": "Cifrado donde se usa la misma clave para encriptar y desencriptar.", "category": "Cryptography", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},

    # T
    {"term_en": "Threat", "term_es": "Amenaza", "definition_en": "A potential cause of an unwanted incident.", "definition_es": "Causa potencial de un incidente no deseado que puede dañar un sistema.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Token", "term_es": "Token", "definition_en": "A device used to obtain access to a computer system.", "definition_es": "Dispositivo físico o digital usado para autenticación.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Trojan Horse", "term_es": "Troyano", "definition_en": "Malware which misleads users of its true intent.", "definition_es": "Malware disfrazado de software legítimo.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Two-Factor Authentication", "term_es": "Autenticación de Dos Factores (2FA)", "acronym": "2FA", "definition_en": "A method of confirming users' claimed identities by using a combination of two different factors.", "definition_es": "Autenticación que requiere dos pruebas de identidad.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # V
    {"term_en": "Virtual Private Network", "term_es": "VPN", "acronym": "VPN", "definition_en": "A network that extends a private network across a public network.", "definition_es": "Red privada extendida sobre una pública (Internet) mediante cifrado.", "category": "Network Security", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Virus", "term_es": "Virus", "definition_en": "A type of computer program that, when executed, replicates itself by modifying other computer programs.", "definition_es": "Programa que infecta otros archivos y se replica al ejecutarse.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Vulnerability", "term_es": "Vulnerabilidad", "definition_en": "A weakness which can be exploited by a threat actor.", "definition_es": "Debilidad o fallo en un sistema que puede ser explotado.", "category": "Fundamentals", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Vulnerability Assessment", "term_es": "Análisis de Vulnerabilidades", "definition_en": "The process of identifying, quantifying, and prioritizing vulnerabilities.", "definition_es": "Proceso de identificar y clasificar las debilidades de un sistema.", "category": "Security Controls", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},

    # W
    {"term_en": "Worm", "term_es": "Gusano", "definition_en": "A standalone malware computer program that replicates itself in order to spread to other computers.", "definition_es": "Malware que se replica y propaga automáticamente por redes.", "category": "Threats", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Whaling", "term_es": "Whaling (Fraude del CEO)", "definition_en": "A phishing attack that targets high-profile employees.", "definition_es": "Phishing dirigido a altos ejecutivos (CEOs) para robar información crítica.", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "White Hat", "term_es": "Hacker de Sombrero Blanco", "definition_en": "An ethical computer hacker.", "definition_es": "Hacker ético que ayuda a mejorar la seguridad.", "category": "Security Controls", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Wi-Fi", "term_es": "Wi-Fi", "definition_en": "Wireless networking technology.", "definition_es": "Tecnología de red inalámbrica.", "category": "Network Security", "difficulty": "beginner", "where_you_hear_it": REF_OFICIAL},

    # Z
    {"term_en": "Zero-Day", "term_es": "Día Cero (0-Day)", "definition_en": "A vulnerability that is unknown to the parties responsible for patching it.", "definition_es": "Vulnerabilidad desconocida para la cual no existe parche.", "category": "Threats", "difficulty": "advanced", "where_you_hear_it": REF_OFICIAL},
    {"term_en": "Zombie", "term_es": "Zombi", "definition_en": "A computer connected to the Internet that has been compromised by a hacker.", "definition_es": "Ordenador controlado remotamente por un atacante (parte de una botnet).", "category": "Threats", "difficulty": "intermediate", "where_you_hear_it": REF_OFICIAL}
]

# --- GUARDADO EN LA CARPETA CORRECTA ---
# Usamos ".." para subir de "backend/scripts" a "backend", y luego entrar a "data"
output_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'glossary_data.json')

# Asegurar que el directorio existe
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(glossary_data, f, indent=2, ensure_ascii=False)

print(f"✅ Archivo generado CORRECTAMENTE en: {output_path}")
print(f"📊 Total de términos: {len(glossary_data)}")